# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import simple_api_pb2 as simple__api__pb2


class SimpleApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Greet = channel.unary_unary(
                '/simple_api.SimpleApi/Greet',
                request_serializer=simple__api__pb2.GreetRequest.SerializeToString,
                response_deserializer=simple__api__pb2.GreetResponse.FromString,
                )


class SimpleApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Greet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimpleApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Greet': grpc.unary_unary_rpc_method_handler(
                    servicer.Greet,
                    request_deserializer=simple__api__pb2.GreetRequest.FromString,
                    response_serializer=simple__api__pb2.GreetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'simple_api.SimpleApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SimpleApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Greet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simple_api.SimpleApi/Greet',
            simple__api__pb2.GreetRequest.SerializeToString,
            simple__api__pb2.GreetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class SquareRootApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Sqrt = channel.unary_unary(
                '/simple_api.SquareRootApi/Sqrt',
                request_serializer=simple__api__pb2.SqrtNumber.SerializeToString,
                response_deserializer=simple__api__pb2.SqrtResponse.FromString,
                )


class SquareRootApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Sqrt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SquareRootApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Sqrt': grpc.unary_unary_rpc_method_handler(
                    servicer.Sqrt,
                    request_deserializer=simple__api__pb2.SqrtNumber.FromString,
                    response_serializer=simple__api__pb2.SqrtResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'simple_api.SquareRootApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SquareRootApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Sqrt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simple_api.SquareRootApi/Sqrt',
            simple__api__pb2.SqrtNumber.SerializeToString,
            simple__api__pb2.SqrtResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
