# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simple_api.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10simple_api.proto\x12\nsimple_api\"\x1c\n\x0cGreetRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"!\n\rGreetResponse\x12\x10\n\x08greeting\x18\x01 \x01(\t\"\x1c\n\nSqrtNumber\x12\x0e\n\x06number\x18\x01 \x01(\x02\"\x1e\n\x0cSqrtResponse\x12\x0e\n\x06number\x18\x01 \x01(\x02\x32I\n\tSimpleApi\x12<\n\x05Greet\x12\x18.simple_api.GreetRequest\x1a\x19.simple_api.GreetResponse2I\n\rSquareRootApi\x12\x38\n\x04Sqrt\x12\x16.simple_api.SqrtNumber\x1a\x18.simple_api.SqrtResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'simple_api_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GREETREQUEST._serialized_start=32
  _GREETREQUEST._serialized_end=60
  _GREETRESPONSE._serialized_start=62
  _GREETRESPONSE._serialized_end=95
  _SQRTNUMBER._serialized_start=97
  _SQRTNUMBER._serialized_end=125
  _SQRTRESPONSE._serialized_start=127
  _SQRTRESPONSE._serialized_end=157
  _SIMPLEAPI._serialized_start=159
  _SIMPLEAPI._serialized_end=232
  _SQUAREROOTAPI._serialized_start=234
  _SQUAREROOTAPI._serialized_end=307
# @@protoc_insertion_point(module_scope)
